### ISSUE TITLE
Пользователь

### ISSUE THREAD

**Issue by Elzar4816** [Iliiasik/Animal-Shelter#2]
Илияс я заметил что в проекте при логине пользователь проверяется на админа что впринципе удовлетворяет логике. Но почему то при создании нового пользователя дефолтное состояние строки isAdmin = null.
_**Из-за чего выходит ошибка проверки на состояние админа:**_
![image](https://github.com/user-attachments/assets/ce74c126-8c55-45cb-9f25-ec372ebfed89)

![image](https://github.com/user-attachments/assets/d9195344-b5e7-4ae2-b16c-987440f2ee80)

**_Как это выглядит в бд:_**
![image](https://github.com/user-attachments/assets/05f05e5e-0197-4945-99ac-276b4fb45801)

Кажется будет лучше если обычное состояние админа будет false раз мы будем настраивать доступ к нему через бд.

**_А также отсутствуют стили css для страницы админ:_**
![image](https://github.com/user-attachments/assets/5d7f2675-d526-40e6-9e2d-fcecfb57b893)

**Comment by Iliiasik** [comment]
Дружище, тут проблема с gorm. Когда я создаю у себя, то дефолт значение - false. Но в твоем варианте именно null. Я это еще на паре тебе говорил. Тебе надо проверить Insert новых пользователей, там найди строку отвечающую за is_admin. Сейчас я поищу

**Comment by Iliiasik** [comment]
Насчет стилей; Очисти кэш браузера (полностью очисть историю). Стили имеют свойство накладываться друг на друга, из-за чего стиль слетает вовсе

**Comment by Iliiasik** [comment]
_, err = db.Exec("INSERT INTO users (username, password, email, email_confirmed, role, confirmation_token) VALUES ($1, $2, $3, $4, $5, $6)", username, string(hashedPassword), email, false, "User", token)
	if err != nil {
		renderError(w, r, "Username or email is already taken")
		return
	}
	
	
	
Вот твой код. Видишь тут поле is_admin просто игнорируется => is_admin == null. Сделай вот так:
в список полей (username, password...... Добавь сюда is_admin). Потом под номером, к примеру ты напишешь is_admin последним, тогда добавишь: $7 и после token добавишь false

**Comment by Iliiasik** [comment]
> Дружище, тут проблема с gorm. Когда я создаю у себя, то дефолт значение - false. Но в твоем варианте именно null. Я это еще на паре тебе говорил. Тебе надо проверить Insert новых пользователей, там найди строку отвечающую за is_admin. Сейчас я поищу

PS: gorm не причем. Ниже я написал почему у тебя ошибка. Просто из за инсерта в дб
